# Dependabot configuration for automated dependency updates
# This file enables security updates and version updates for all detected package ecosystems
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # .NET NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    # Limit number of open Dependabot PRs to reduce noise
    open-pull-requests-limit: 5
    # Assign PRs to the octocat-reviewers team
    reviewers:
      - "octocat-reviewers"
    assignees:
      - "devtobecurious"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Add security-management label to all PRs + existing labels
    labels:
      - "security-management"
      - "dependencies"
      - "nuget"
    # Allow only production dependencies, ignore dev dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore development dependencies completely
    ignore:
      - dependency-name: "*"
        dependency-type: "development"
      # Also ignore major version updates for non-security updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    versioning-strategy: increase

  # GitHub Actions workflows (for future CI/CD pipelines)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    # Limit number of open GitHub Actions PRs
    open-pull-requests-limit: 3
    # Assign PRs to the octocat-reviewers team
    reviewers:
      - "octocat-reviewers"
    assignees:
      - "devtobecurious"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Add security-management label to all PRs + existing labels
    labels:
      - "security-management"
      - "dependencies"
      - "github-actions"
      - "ci/cd"