# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'
  AWS_REGION: 'us-east-1'
  ECS_CLUSTER: 'production'
  ECS_SERVICE: 'api-service'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # Retirer cache si pas de package-lock.json
          # OU ajouter cache seulement si le fichier existe
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm ci
        # Si pas de package-lock.json, utiliser : npm install
      
      - name: Run linter
        run: npm run lint
      
      - name: Run tests
        id: tests
        run: npm test -- --coverage
        continue-on-error: true
      
      - name: Create issue for test failures
        if: steps.tests.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🔴 Test failures in build #${{ github.run_number }}`,
              body: `## Test Failures Detected
              
              **Workflow Run:** [${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
              **Branch:** \`${{ github.ref_name }}\`
              **Commit:** ${{ github.sha }}
              **Triggered by:** @${{ github.actor }}
              
              ---
              
              @github Please investigate and fix these test failures.
              
              ## Your Tasks
              1. Analyze the failing tests in the workflow logs
              2. Determine root cause (code bug vs test bug)
              3. Implement the fix
              4. Ensure all tests pass
              5. Create a PR with your fix
              
              ## Requirements
              - Follow coding standards in .github/copilot-instructions.md
              - Maintain or improve test coverage
              - Add additional tests if edge cases found
              - Update documentation if behavior changes
              
              ## Acceptance Criteria
              - [ ] All tests pass
              - [ ] No new linting errors
              - [ ] Coverage maintained or improved
              - [ ] PR created and ready for review
              
              **Priority:** High
              `,
              labels: ['bug', 'tests', 'copilot-agent', 'high-priority'],
              assignees: ['github']
            });
